version: '3.9'

services:
  feedback-db:
    container_name: feedback-db
    image: mongo
    networks: 
      - default
    ports: 
      - "27017:27017"
    volumes: 
      - mongodbdata:/data/db

  feedback-service:
    container_name: feedback-service
    build:
      context: .
      dockerfile: Feedback-Service/Dockerfile
    ports:
      - 5005:80
    networks:
      - default
    environment:
      ASPNETCORE_ENVIRONMENT: Staging

networks:
  default:
    name: mira

volumes:
  mongodbdata: